### ISSUE TITLE
Update before read

### ISSUE THREAD

**Issue by olliephillips** [traetox/goDS18B20#1]
Thanks for this package I will be using. 

One question though. It took me a while to understand why I was getting 0.00c temp reports, then I found that the actual `w1_slave` temp file is parsed in the `Update()` method, so that needs to be called first. I was just interested to understand why this is, and why the whole parse and report is not part of the `Read*()` functions & methods. 

Thanks again for the writing the package!

**Comment by traetox** [comment]
eeeh, bad design?  It probably should all be done in the Read function.

**Comment by traetox** [comment]
Addressing in commit e88a0586421696ea82d5c9c94416ccdc60e918a9

Now, just issue a Read() or ReadAlias(), no need to call Update().

**Comment by olliephillips** [comment]
Cheers!
